algorithm =
    "algoritmo" identifier ";"

    "início"
        {sentence}*
    "fim"
    ;

sentence =
    library_call | assignment
    ;

library_call =
    identifier "(" {arguments}* ")" ";"
    ;
 
identifier = alphabetic-character { alphabetic-character | digit | "_" }* ;
number = [ "-" ] { digit }+ ;
string = '"' { all-characters - ('"' | "\r" | "\n") }, '"' ;
assignment = identifier ":=" ( number | identifier | string ) ;
alphabetic character = "A" | "B" | "C" | "D" | "E" | "F" | "G"
                      | "H" | "I" | "J" | "K" | "L" | "M" | "N"
                      | "O" | "P" | "Q" | "R" | "S" | "T" | "U"
                      | "V" | "W" | "X" | "Y" | "Z" ;
digit = "0" | "1" | "2" | "3" | "4" | "5" | "6" | "7" | "8" | "9" ;
white-space = " " | "\r" | "\n" | "\t ;
all-characters = ? all visible characters ? ;
